[package]
authors = ["Xuanwo <github@xuanwo.io>>"]
categories = ["command-line-utilities"]
description = "hickory resolver support for reqwest"
documentation = "https://docs.rs/reqwest-hickory-resolver"
repository = "https://github.com/Xuanwo/reqwest-hickory-resolver"
edition = "2021"
license = "Apache-2.0"
name = "reqwest-hickory-resolver"
version = "0.1.0"

[dependencies]
hickory-resolver = "0.24"
reqwest = { version = "0.12", default-features = false }
once_cell = "1.19.0"
rand = { version = "0.9", features = ["small_rng"] }